"""The FastAPI app: REST API, the phone app's files, and the scheduler.

Run it with:  uvicorn app.main:app --reload
Interactive API docs (generated by FastAPI): http://localhost:8000/docs
"""

import asyncio
import logging
import time
from contextlib import asynccontextmanager
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Literal
from zoneinfo import ZoneInfo

from fastapi import FastAPI, Header, HTTPException, Query
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field, field_validator

from .config import settings
from .models import Article
from .pipeline import refresh, run_edition_if_due, run_scheduled
from .push import DEFAULT_PREFS, LEVELS, SubscriptionGone, init_push, send_to, vapid_public_key
from .relevance import CATEGORIES, rank_score
from .store import load_articles, load_subscriptions, remove_subscription, store, upsert_subscription

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s [%(name)s] %(message)s")
log = logging.getLogger("app")

STATIC_DIR = Path(__file__).resolve().parent.parent / "static"
PAGE_SIZE = 20


# ---- Startup, shutdown and the scheduler ------------------------------------------


async def scheduler() -> None:
    """Background loop. Edition mode checks every 10 minutes whether today's
    edition is due; continuous mode refreshes every REFRESH_MINUTES."""
    interval = 10 * 60 if settings.edition_mode else settings.refresh_minutes * 60
    while True:
        try:
            await run_scheduled()
        except Exception:
            log.exception("scheduled run failed")
        await asyncio.sleep(interval)


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Runs once when the server starts...
    store.init()
    init_push()
    if settings.edition_mode:
        log.info("daily edition: top %d stories at %d:00 %s", settings.stories_per_day, settings.edition_hour, settings.edition_timezone)
    task = asyncio.create_task(scheduler()) if settings.scheduler_enabled else None
    yield
    # ...and once when it stops.
    if task:
        task.cancel()
    store.close()


app = FastAPI(title="AI Shorts", description="AI news in 60 words", lifespan=lifespan)


# ---- Reading news -------------------------------------------------------------


def filter_by_tab(articles: list[Article], tab: str | None) -> list[Article]:
    if tab == "today":
        latest = max((a.edition for a in articles if a.edition), default=None)
        return sorted((a for a in articles if latest and a.edition == latest), key=lambda a: a.edition_rank or 0)
    if tab == "top":
        return sorted(articles, key=rank_score, reverse=True)
    if tab == "breaking":
        cutoff = datetime.now(timezone.utc) - timedelta(hours=48)
        return [a for a in articles if (a.breaking or a.relevance >= 9) and a.published_at > cutoff]
    if tab == "deep":
        return [a for a in articles if a.category == "explainer" or a.source_kind in ("analysis", "medium")]
    if tab in CATEGORIES:
        return [a for a in articles if a.category == tab]
    return articles  # "all" / no tab: newest first


@app.get("/api/meta")
def meta():
    """Everything the phone app needs to set itself up."""
    edition = (
        {"perDay": settings.stories_per_day, "hour": settings.edition_hour, "timezone": settings.edition_timezone}
        if settings.edition_mode
        else None
    )
    return {
        "categories": CATEGORIES,
        "levels": {key: level["label"] for key, level in LEVELS.items()},
        "defaultPrefs": DEFAULT_PREFS,
        "vapidPublicKey": vapid_public_key(),
        "lastRefresh": store.get("last-refresh"),
        "edition": edition,
    }


@app.get("/api/news")
def news(
    tab: str | None = None,
    topics: str = "",
    offset: int = Query(0, ge=0),
    since: datetime | None = None,
):
    """A page of stories for a tab, e.g. /api/news?tab=today"""
    articles = load_articles()
    topic_list = [t for t in topics.split(",") if t]
    if topic_list and not tab:
        articles = [a for a in articles if a.category in topic_list]
    articles = filter_by_tab(articles, tab)
    new_since = 0
    if since:
        since = since if since.tzinfo else since.replace(tzinfo=timezone.utc)
        new_since = sum(1 for a in articles if a.briefed_at > since)
    return {
        "total": len(articles),
        "newSince": new_since,
        "items": [a.to_json() for a in articles[offset : offset + PAGE_SIZE]],
    }


@app.get("/api/news/{article_id}")
def one_story(article_id: str):
    for article in load_articles():
        if article.id == article_id:
            return article.to_json()
    raise HTTPException(status_code=404, detail="not found")


# ---- Notifications ------------------------------------------------------------
# Request bodies are pydantic models: FastAPI validates them automatically and
# answers 422 with a helpful message if something is missing or malformed.


class PushKeys(BaseModel):
    p256dh: str
    auth: str


class PushSubscription(BaseModel):
    endpoint: str = Field(max_length=1000)
    keys: PushKeys

    @field_validator("endpoint")
    @classmethod
    def must_be_https(cls, value: str) -> str:
        if not value.startswith("https://"):
            raise ValueError("endpoint must be an https URL")
        return value


class Prefs(BaseModel):
    level: Literal["breaking", "top", "all", "off"] = "top"
    topics: list[str] = []
    maxPerDay: int = Field(6, ge=1, le=30)
    quietStart: int = Field(22, ge=0, le=23)
    quietEnd: int = Field(7, ge=0, le=23)
    timezone: str = "UTC"

    @field_validator("topics")
    @classmethod
    def known_topics(cls, value: list[str]) -> list[str]:
        return [t for t in value if t in CATEGORIES]

    @field_validator("timezone")
    @classmethod
    def known_timezone(cls, value: str) -> str:
        try:
            ZoneInfo(value)
            return value
        except Exception:
            return "UTC"


class SubscribeBody(BaseModel):
    subscription: PushSubscription
    prefs: Prefs = Prefs()


class EndpointBody(BaseModel):
    endpoint: str


@app.post("/api/subscribe")
def subscribe(body: SubscribeBody):
    """Save a phone's push subscription. Sending it again updates the preferences."""
    saved = upsert_subscription(body.subscription.endpoint, body.subscription.keys.model_dump(), body.prefs.model_dump())
    return {"ok": True, "prefs": saved["prefs"]}


@app.post("/api/unsubscribe")
def unsubscribe(body: EndpointBody):
    return {"ok": remove_subscription(body.endpoint)}


_last_test: dict[str, float] = {}


@app.post("/api/test-push")
async def test_push(body: EndpointBody):
    """The "Send test" button."""
    sub = next((s for s in load_subscriptions() if s["endpoint"] == body.endpoint), None)
    if sub is None:
        raise HTTPException(404, "subscribe first")
    if time.time() - _last_test.get(body.endpoint, 0) < 15:
        raise HTTPException(429, "wait a few seconds")
    _last_test[body.endpoint] = time.time()
    top = max(load_articles(), key=lambda a: a.relevance, default=None)
    payload = {
        "title": "Notifications are on ✅",
        "body": f"Top story right now: {top.headline}" if top else "You'll get your daily AI stories here.",
        "url": f"/?story={top.id}" if top else "/",
        "tag": "test",
    }
    try:
        await send_to(sub, payload)
    except SubscriptionGone:
        remove_subscription(body.endpoint)
        raise HTTPException(410, "subscription expired; turn notifications on again")
    except Exception as exc:
        raise HTTPException(502, str(exc)[:200])
    return {"ok": True}


# ---- Admin and health -----------------------------------------------------------


@app.post("/api/refresh")
async def admin_refresh(authorization: str = Header("")):
    """Run the pipeline now. Needs ADMIN_TOKEN: `Authorization: Bearer <token>`."""
    if not settings.admin_token or authorization != f"Bearer {settings.admin_token}":
        raise HTTPException(401, "unauthorized")
    return await run_edition_if_due(force=True) if settings.edition_mode else await refresh()


@app.get("/healthz")
def health():
    return {"ok": True}


# ---- The phone app (static files) ------------------------------------------------


@app.get("/sw.js", include_in_schema=False)
def service_worker():
    # The service worker must always be re-checked so app updates reach phones.
    return FileResponse(STATIC_DIR / "sw.js", media_type="text/javascript", headers={"cache-control": "no-cache"})


# Mounted last so the /api routes above take priority. html=True serves
# index.html for "/".
app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")

# httpx logs every page it downloads; only show problems.
logging.getLogger("httpx").setLevel(logging.WARNING)
